Feature 91 main page추가
Sprint-8-2/KNOCK pull request #121
Opened 2024-07-19 12:31 UTC by SeungHyunOK

# 작업분류

- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 리팩토링
- [ ] 기타

# 작업개요

- main page추가
- MainPageInput 컴포넌트 수정사항 반영 
- Input.module.scss-width 크기 이전 상태로 수정

# 작업 상세 내용

- MainPageInput 컴포넌트 의 API 처리를 MainPage로 이동

# 리뷰 요구사항

- API 처리 부분을 잘했는지 봐주세요.

# 기타

#74 수정 
#91

2024-07-19 13:51 UTC, L1m3Kun requested changes
메인 페이지의 기능이 잘못 연결되어 있는 것 같은데 확인 부탁드립니다 😄

2024-07-19 13:51 UTC, L1m3Kun commented on knock/src/pages/MainPage.tsx
> +        />
아이콘 태그를 사용해보시는건 어떤가요??
```suggestion
        <Icon
          src={rightArrow}
          alt="rightArrow"
          imageClassName={styles['mainPage__answer__rightArrowImg']}
        />
```

2024-07-19 13:51 UTC, L1m3Kun commented on knock/src/pages/MainPage.tsx
> +      >
버튼을 누르면 로직없이 페이지 이동만 있는걸로 알고있는데 혹시 제가 잘못 알고 있는걸까요?

2024-07-19 13:51 UTC, L1m3Kun commented on knock/src/pages/MainPage.tsx
> +  };
이 로직들은 MainPageInput에 있어야 관심사 분리에 더 적합한것 같아요!

2024-07-19 13:57 UTC, SeungHyunOK commented on knock/src/pages/MainPage.tsx
> +        />
감사합니다!

2024-07-19 13:58 UTC, SeungHyunOK commented on knock/src/pages/MainPage.tsx
> +      >
저가 잘못 알고있었어요 ㅎㅎ 감삽합니다 바로 수정하겠습니다!

2024-07-19 14:03 UTC, SeungHyunOK commented on knock/src/pages/MainPage.tsx
> +  };
언제나 소중한 리뷰 감사합니다, 성구님 덕분에 많이 배움니다.

2024-07-20 05:44 UTC, L1m3Kun approved these changes

2024-07-20 05:54 UTC, wonsik3686 approved these changes

2024-07-20 05:59 UTC, merged