Feature 10 dropdown컴포넌트추가
Sprint-8-2/KNOCK pull request #21
Opened 2024-07-11 14:16 UTC by L1m3Kun

# 작업분류

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 리팩토링
- [ ] 기타

# 작업개요
- Dropdown 컴포넌트 추가

# 작업 상세 내용
- Dropdown 컴포넌트 및 DropdownContent 컴포넌트 추가
- Dropdown open/close 기능 구현
- scss를 통한 css 스타일링
- Dropdown 요소가 `string` 타입일 경우, `selected`와 비교하여 선택 요소 처리(blue 색상처리)
- hover / active 에 대한 ui 처리

# 리뷰 요구사항
- 사용하기 편한 방식인가를 확인해주세요
- 구현 방식에 대한 이야기를 해주시면 감사합니다.
- SCSS, BEM에 관련되서 잘못된 점이나 이상한 점이 있으면 말씀해주세요

# 기타

- 사용법
  - props
    - `children`: 드랍다운 버튼에 들어가는 요소(ex-버튼/최신순/이름순/아이콘)
    - `dropdownElementList`: 드랍다운을 클릭했을 때 아래로 내려오는 요소들(`React.ReactNode[] | string[]` 타입)
    - `handleSelectElement` 드랍다운 요소를 클릭했을 때 호출되는 함수
    - `selected?`: 드랍다운을 선택용으로 사용할 때, 드랍다운 요소가 현재 선택된 요소인지 판별하기 위한 변수(ex- `이름순`일 경우, `이름순`이라는 요소가 파란색으로 변경)

  - 아이콘을 같이 넣을 수 있도록 `string`타입과 `React.ReactNode` 타입을 병행하여 확장성을 높였습니다.
  - 예시 이미지
![스크린샷 2024-07-11 오후 11 16 01](https://github.com/Sprint-8-2/KNOCK/assets/113879996/4a0748a5-6df0-43e1-82fb-c41f55cdd325)

2024-07-11 23:28 UTC, wonsik3686 requested changes
className 에서 styles 객체 사용 확인 부탁드립니다

2024-07-11 23:28 UTC, wonsik3686 commented on knock/src/core/ui/Dropdown/Dropdown.tsx
> +    <div className="dropdown">
className 에서 styles 사용 안하신 이유가 있을까요?

2024-07-12 01:33 UTC, L1m3Kun commented on knock/src/core/ui/Dropdown/Dropdown.tsx
> +    <div className="dropdown">
놓친 내용이었는데 감사합니다!!
이전에 style을 사용하지 않고 직접 import 하는 방식에서 styles 객체로 바꾸는 중에 놓친 부분이네요.
검토해서 commit 넣겠습니다 :)

2024-07-12 02:34 UTC, wonsik3686 approved these changes

2024-07-12 02:35 UTC, leesh7048 approved these changes

2024-07-12 02:37 UTC, merged