feat: 공통 image 컴포넌트 로직 추가
Sprint-8-2/KNOCK pull request #23
Opened 2024-07-11 16:26 UTC by jangyonghan

# 작업분류

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 리팩토링
- [ ] 기타

# 작업개요

- image 컴포넌트 추가

# 작업 상세 내용

- EmptyQuestion 컴포넌트 추가
- FeedHeaderImage 컴포넌트 추가
- MainImage 컴포넌트 추가
- MainLogo 컴포넌트 추가
- ProfilePhoto 컴포넌트 추가

# 리뷰 요구사항

- 처음 공통 컴포넌트를 만든거라 이렇게 작성하는게 맞는지.. 각 컴포넌트별 피드백좀 부탁드립니다..!

# 기타

2024-07-11 23:45 UTC, wonsik3686 reviewed
- 패키지 수정 설명
- scss module styles 객체 사용
-  각 컴포넌트에 대해서 폴더화
- 이미지를 prop 으로 받아서 공통적으로 사용할 수 있도록 공통 컴포넌트를 개발

위 사항들 한 번 확인 부탁드립니다

2024-07-11 23:45 UTC, wonsik3686 commented on knock/package.json
> -    "node-sass": "^7.0.3",
패키지 수정 이유가 있을까요?

2024-07-12 01:06 UTC, L1m3Kun requested changes

2024-07-12 01:06 UTC, L1m3Kun commented on knock/src/core/ui/image/MainImage.module.scss
> +
reset css 적용되면 body에 들어가 있는 스타일은 지워도 괜찮아 보입니다!

2024-07-12 01:06 UTC, L1m3Kun commented on knock/src/core/ui/image/MainLogo.tsx
> +        style={{ width, height, margin }}
직접 스타일을 넣는건 권장되지 않는 사항이라서 다른 방식을 고안하면 좋을 것 같습니다 😃 

인라인 방식으로 작성하는 스타일은 저희가 알고 있는 css적용 방식과 다르다고 알고 있는데 이런 부분들이 나중에 디버깅에 어려움을 준다고 알고 있습니다

2024-07-12 01:06 UTC, L1m3Kun commented on knock/src/core/ui/image/ProfilePhoto.tsx
> +        style={{ width, height }}
인라인 스타일 대신 다른 방식을 사용해보는건 어떠신가요??

2024-07-12 02:36 UTC, merged

2024-07-12 03:07 UTC, jangyonghan commented on knock/src/core/ui/image/ProfilePhoto.tsx
> +        style={{ width, height }}
어떤 방식을 사용해야할까요..ㅠㅠ
이미지 크기를 동적으로 주고싶었는데 다른 방법으로 어떻게 해야할지 모르겠네요..
아니면 스타일은 인라인으로 주지 않고 기본 스타일만 SCSS로 만들어놓고
사용하시는 분들이 자유롭게 스타일을 줄수 있도록 해야할까요??

2024-07-12 04:38 UTC, L1m3Kun commented on knock/src/core/ui/image/ProfilePhoto.tsx
> +        style={{ width, height }}
scss 특성상 동적으로 넣어줄 순 없어보입니다 기본 100%로 맞춰서  wrapper로 감싸 사용하거나 선택지를 만들어 놓는 정도가 어떨지 생각됩니다