Feature 40 공통toast컴포넌트추가
Sprint-8-2/KNOCK pull request #49
Opened 2024-07-14 17:12 UTC by SeungHyunOK

# 작업분류

- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 리팩토링
- [ ] 기타

# 작업개요

_주요 작업 내용에 대한 요약설명_

# 작업 상세 내용

_작업 개요에 작성한 내용에 대한 상세 항목_
_주요 기능 및 로직에 대해 간결하게 작성_

# 리뷰 요구사항

_집중 리뷰 부분 작성_

# 기타

_관련된 이슈가 있다면, PR 작성 맨 아래에서 이슈 연결 키워드도 작성해 주세요._
_예시: Closes #10, Fixes octo-org/octo=repo#100, Resolves #10, resolves #123, resolves octo-org/octo-repo#100_

2024-07-15 00:37 UTC, L1m3Kun commented on knock/src/core/ui/Toast/Toast.tsx
> +        </div>
URL이 복사되었습니다 부분은 동적으로 할당하는게 UX 적인 관점에서 더 효과적인 것 같은데 어떻게 생각하시나요??
```suggestion
        <div className={`${styles['layout']}`}>
          <div className={`${styles['text']}`}>{토스트_메세지}</div>
        </div>
```

2024-07-15 00:37 UTC, L1m3Kun commented on knock/src/core/ui/Toast/Toast.tsx
> +
기능 부분을 상위에서 다루는게 더 편할 것 같은데 어떻게 생각하시나요?? 😄
```suggestion
interface ToastProps {
  토스트_나타내기_상태값: boolean;
  토스트_메세지: string;
}
const Toast: React.FC<ToastProps> = ({토스트_나타내기_상태값, 토스트_메세지}) => {
```

2024-07-15 03:50 UTC, wonsik3686 reviewed
성구님이 남겨주신 내용이 수정되면 좋을 것 같습니다

2024-07-15 07:28 UTC, L1m3Kun requested changes

2024-07-15 07:28 UTC, L1m3Kun commented on knock/src/core/ui/Toast/Toast.tsx
> +  }, [showToast]);
이 기능은 상위 컴포넌트에서 하는게 더 낫지 않을까요?? 해당 컴포넌트는 UI만 구현하면 더 편하게 사용할 수 있을 것 같아요!😄

2024-07-15 07:28 UTC, L1m3Kun commented on knock/src/core/ui/Toast/Toast.tsx
> +}
props와 같이 볼 수 있게 상위로 올려주시면 파일 확인할 때 편할 것 같습니다 👍

2024-07-15 07:46 UTC, wonsik3686 requested changes
성구님이 요청하신 사항 해결되면 머지해도 될 것 같습니다

2024-07-15 08:37 UTC, L1m3Kun commented on knock/src/core/styles/toast.module.scss
> +  height: 2.625rem;
글자가 길어지면 어떤식으로 작동하나요?

2024-07-16 05:00 UTC, wonsik3686 approved these changes

2024-07-16 05:15 UTC, L1m3Kun commented on knock/src/core/styles/toast.module.scss
> +  height: 2.625rem;
혹시 이 부분은 확인하셨을까요??

2024-07-16 06:23 UTC, L1m3Kun approved these changes

2024-07-16 06:24 UTC, merged