Feature 74 메인페이지input컴포넌트추가
Sprint-8-2/KNOCK pull request #97
Opened 2024-07-18 04:16 UTC by SeungHyunOK

# 작업분류

- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 리팩토링
- [ ] 기타

# 작업개요

메인페이지input컴포넌트추가

# 작업 상세 내용

- ```
<MainPageInput
        onSubmit={handleSubmit}
        placeholder="이름을 입력하세요"
        submitButtonText="질문 받기"
      /> 
```이렇게 사용
- 
<img width="541" alt="스크린샷 2024-07-15 16 02 26" src="https://github.com/user-attachments/assets/a1d56db7-4951-4806-bf2d-4fa28eafbb44">

# 리뷰 요구사항

-api 보내는 부분 확인부탁드립니다.

# 기타

-
<img width="1710" alt="스크린샷 2024-07-18 10 57 20" src="https://github.com/user-attachments/assets/b2c04592-cc10-4498-b675-729f2078bfe5">
클릭을 하면 이런 에러가 나지만 홈페이지를 만들고 처리하겠습니다.
#74

2024-07-18 05:11 UTC, L1m3Kun requested changes
공용 컴포넌트나 만들어둔 기능들을 활용하지 않은 이유가 있을까요?? 😂

2024-07-18 05:11 UTC, L1m3Kun commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +      const response = (await apiHandler.post('your-endpoint', {
혹시 api handler를 직접 가져와서 쓰신 이유가 있을까요?? 
미리 다 api에 관해서 작업 다 만들어놨었는데 부족한 점이 있었을까요??? 😂

2024-07-18 05:11 UTC, L1m3Kun commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +        />
input 공용 컴포넌트도 안쓰신 이유가 있을까요??

2024-07-18 06:00 UTC, wonsik3686 requested changes
성구님이 남겨준 수정사항 빠르게 적용해보면 좋을 것 같아요
화이팅입니다 😀

2024-07-18 06:23 UTC, SeungHyunOK commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +      const response = (await apiHandler.post('your-endpoint', {
확인하고 수정하겠습니다~!

2024-07-18 13:36 UTC, L1m3Kun commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +const MainPageInput: React.FC<MainPageInputProps> = ({ onSubmit }) => {
onSubmit 용도가 없으면 빼도 괜찮을 것 같습니다! 😄

2024-07-18 13:36 UTC, L1m3Kun commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +    }
빈 값일때는 handleSubmit이 작동하지 않게 하는 것도 좋아보입니다!😄
```suggestion
    if (name && e.key === 'Enter') {
      handleSubmit(e);
    }
```

2024-07-18 13:36 UTC, L1m3Kun commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +          />
공통 컴포넌트 Icon 컴포넌트를 사용하지 않은 이유가 있으신가요??

2024-07-18 13:52 UTC, SeungHyunOK commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +const MainPageInput: React.FC<MainPageInputProps> = ({ onSubmit }) => {
감사합니다! 😊

2024-07-18 13:54 UTC, SeungHyunOK commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +          />
까먹었습니다ㅠㅠ 바로 적용해 볼게요!

2024-07-19 04:40 UTC, L1m3Kun commented on knock/src/components/MainPageInput/MainPageInput.tsx
> +interface MainPageInputProps {}
필요없는 사항들은 지워주셔도 괜찮을 것 같습니다! 😄

2024-07-19 09:20 UTC, SeungHyunOK commented on knock/src/core/styles/input.module.scss
> -  width: 100%;
생각해보니깐 그렇내요 좋은 지적 감사합니다

2024-07-20 05:49 UTC, wonsik3686 requested changes
@SeungHyunOK 
https://github.com/Sprint-8-2/KNOCK/pull/121
이후에 올리신 위 PR 과 내용이 겹친다면 이 PR 은 닫아도 될까요?

2024-07-20 05:59 UTC, merged